version: '3.8'

services:
  # 프론트엔드 (PHP-Apache)
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - project-net
    volumes:
      - ./frontend:/var/www/html/

  # 백엔드 (Node.js)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - project-net
    depends_on:
      - db
      - ai_server

  # AI 서버 (FastAPI)
  ai_server:
    build: ./ai_server
    ports:
      - "8000:8000"
    networks:
      - project-net

  # DB 서버 (MySQL)
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recommendation_db
    ports:
      - "3306:3306"
    networks:
      - project-net

networks:
  project-net:
    driver: bridge
