version: '3.8'

services:
  # 프론트엔드 (PHP-Apache)
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - project-net
    # 오류가 발생할 수 있는 포트나 환경 변수를 추가
    volumes:
      - ./frontend:/var/www/html

  # 백엔드 (Node.js)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - project-net
    environment:
      - DB_HOST=db
      - DB_USER=toxh13
      - DB_PASSWORD=123123a
      - DB_NAME=project_db
    depends_on:
      - db
    volumes:
      - ./backend:/app  # 코드 변경 반영을 위해 볼륨 설
  # AI 서버 (FastAPI)
  ai_server:
    build: ./AI
    ports:
      - "8000:8000"
    networks:
      - project-net
    environment:
      AI_MODEL_PATH: ""  # 비워놓은 상태
    volumes:
      - ./AI:/app  # AI 폴더를 컨테이너에 매핑
    depends_on:
      - db  # DB가 필요할 경우 DB와 연결B가 필요할 경우 DB와 연결
  # DB 서버 (MySQL)
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123123123a
      MYSQL_DATABASE: project_db
      MYSQL_USER: toxh13
      MYSQL_PASSWORD: 123123a
    ports:
      - "3306:3306"
    networks:
      - project-net
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  project-net:
    driver: bridge
