version: '3.8'

services:
  # 프론트엔드 (PHP-Apache)
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - project-net
    # 오류가 발생할 수 있는 포트나 환경 변수를 추가

  # 백엔드 (Node.js)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - project-net
    depends_on:
      - db
      - ai_server
    environment:
      - DB_HOST=db # DB 서버의 호스트 이름
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=recommendation_db

  # AI 서버 (FastAPI)
  ai_server:
    build: ./AI
    ports:
      - "8000:8000"
    networks:
      - project-net
    environment:
      - AI_MODEL_PATH=/path/to/model  # 모델 경로 설정 (필요시)

  # DB 서버 (MySQL)
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recommendation_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - project-net
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  project-net:
    driver: bridge
